### ISSUE TITLE
Slight Offset

### ISSUE THREAD

**Issue by ermiyaeskandary** [ermiyaeskandary/Slither.io-bot#17]
Slight offset when converting from canvas to screen so issue lies in : 

```
window.screenToCanvas = function(x, y) {
    var canvasX = window.csc * x * window.canvasRatio[0] - window.csc * parseInt(window.mc.style.left);
    var canvasY = window.csc * y * window.canvasRatio[1] - window.csc * parseInt(window.mc.style.top);
    return [canvasX, canvasY];
};
```

This small offset causes issues with the visual element and other things. Variables which stores offset is unknown.

**Comment by Evanito** [comment]
To save CPU cycles, I simplified this with:

```
    var canvasX = window.csc * (x * window.canvasRatio[0] - parseInt(window.mc.style.left));
    var canvasY = window.csc * (y * window.canvasRatio[1] - parseInt(window.mc.style.top));
```

And then found I could almost cancel out the offset by adding a set number such as:

```
    var canvasX = window.csc * (x * window.canvasRatio[0] - parseInt(window.mc.style.left) + 100);
    var canvasY = window.csc * (y * window.canvasRatio[1] - parseInt(window.mc.style.top) - 90);
```

Which worked for me. There is probably a perfect ratio relative to canvasRatio that fixes the offset, since once I resized the window the offset was back with a vengeance.

**Comment by K00sKlust** [comment]
Why is height used for X and width used for Y? Is this not a bug caused by inverting height and width?

![rectxy](https://cloud.githubusercontent.com/assets/14361645/14885441/a71da4ba-0d4b-11e6-904e-255f8a7e1ce3.png)

I think this because resizing the window vertically, makes the dot's move horizontally, but not vertically.

**Comment by K00sKlust** [comment]
Also, if the window is a perfect square, there are no problems

**Comment by ermiyaeskandary** [comment]
Any updates ?

**Comment by tjbcg** [comment]
> And then found I could almost cancel out the offset by adding a set number

I found this too. 

I kept the developped version on purpose, because it isn't clear if window.csc should be used, or if window.gsc should (only for the second term).

**Comment by ErmiyaEskandary** [comment]
@FliiFe Can't we just use a set number as close as possible ? This is just wasting time IMHO.

**Comment by K00sKlust** [comment]
Fixed it! It _was_ a bug caused by inverting x and y :smile:. Updating the code..
