### ISSUE TITLE
Teleportation - Choose Start Location on the Map

### ISSUE THREAD

**Issue by Seple** [ermiyaeskandary/Slither.io-bot#241]
Please new setup/options start at any specific location: X/Y Start play location on the map.
Is it possible?

**Comment by tyschnoor** [comment]
@Seple :heart: it

**Comment by Drflash55** [comment]
I'm not sure if you can program the bot to have you spawn at the same location, because that's determined by the game. You would have to, again, modify the game, in order for you to spawn at your desired location... I don't believe this would be possible by just the bot alone, as it just seems far-fetched.

Don't get me wrong... I love the idea, but I don't see it being a reality, without modifying the game's code to have it work that way...

**Comment by Seple** [comment]
Just a suggestion and question cordial request
I understand that you can not... :(

**Comment by tyschnoor** [comment]
@Seple I've felt the same way #208 
(The whole thing isn't there)

**Comment by Seple** [comment]
The challenge for authors ; )
The master maybe able to do this ... ?
Please :heart:

**Comment by ChadSki** [comment]
There is another userscript that allows you to sorta-teleport by suiciding until you're in a location you like.

**Comment by Seple** [comment]
I have not seen "compatible" with another code...

**Comment by ChadSki** [comment]
I mean, it's possible to implement the feature if someone else has managed to do it.

Using both scripts at the same time would probably not work, true.

**Comment by ermiyaeskandary** [comment]
@ChadSki Could you show me the link ?

**Comment by ermiyaeskandary** [comment]
Teleporting directly wouldn't be possible but suiciding until you are close to your target? We would have to use this at the beginning as it would teleport us with starting length.

**Comment by Seple** [comment]
**_The game starts in a particular place or location is possible?_**

Maybe? "divination XD"
- Add Start Menu - location MAP: X/Y 
- or comand - mid, center, left, right , up, down. 
- teleport - near food.

**Comment by ChadSki** [comment]
Here's one https://www.youtube.com/watch?v=_4IqUnfQHfQ

http://pastebin.com/A6pq3u3Y Edit: Yuck, obfuscated javascript... `eval(String.fromCharCode(`

Lol at the YouTube comments:

> A: the thing is it teleports u ok but it takes u back to ur starting mas﻿
> B: I know that sucks 😕 it is something that needs to be worked on﻿

As if that's a bug that could be fixed. Teleporting at full mass doesn't seem possible. Or if it is possible, it's a blatant hack.

**Comment by WJKH** [comment]
@ChadSki it's just a quick respawn, nothing else.
Press ESC till you get some good position.

**Comment by Seple** [comment]
> Press ESC till you get some good position.

now so I do but very rarely my snake at your desired location middle map or center, left, right , up, down. :/

**Comment by Salvationdk** [comment]
problem with this is, that you cannot be sure to stay on the same server if you suicide more than 5 times i think. i have experienced that the server refused my connection and send me to another server ip.

**Comment by Seple** [comment]
The problem issue is not IP server.  Only start the game in a certain place and on the specific map desired location.

**Comment by ChadSki** [comment]
Is it possible to tell the server where you want to spawn? Or kinda "trick" it into spawning you there?

**Comment by pllsner** [comment]
tools to unobfuscate.
http://matthewfl.com/unPacker.html
copy and paste that obfuscated scipt here, unpack it. and you can see what they did.
Javascript unpacker and beautifier
http://alexis.m2osw.com/js-beautify/

**Comment by ermiyaeskandary** [comment]
@pllsner Cheers! Helps alot!

**Comment by pllsner** [comment]
glad i could help.

**Comment by clemens-tolboom** [comment]
I was wondering how to **move** to a certain point? It kinda _slow teleport_

The other day I played in the same arena using https://github.com/LukeeeeBennett/slither-nest against my bot which was nice (but not yet video worthy)

**Comment by ermiyaeskandary** [comment]
We can't directly teleport as that would be fooling the game..
The only way I see to "teleport" is continuously respawning until you are within a specific section, region, server ?

**Comment by Salvationdk** [comment]
pressing esc many times also gives the possibility to lag the server join, as it tends to hang on server change.

**Comment by I-am-MR-NATE** [comment]
## Really LOVE the idea!

**_Is there really no way?_**

If it really is impossible to input a set of co-ordinates and just spawn there then could the co-ordinates be put into the bot if a box were to be added in the top left where the toggle options are so that the bot would either **SLOW TRAVEL**?

OR if that is not possible, could the ESC quit and rejoin option be automated so that the bot is able to detect when you are within a certain radius of your desired location?

If that were to be possible and were implemented, Further development could possibly make it so that you stick to the same server (possibly by adding and using a toggle?)

**Comment by phrokton** [comment]
In the task execution branch

Would it be better to have : 

_Seek coord, until food density greater than, resume when food density less than_


Additionally in seek coord mode I have watched snake plough through piles of food ignoring the bounty.

**Comment by ChadSki** [comment]
@I-am-MR-NATE why don't you look into it? :smile: Sounds like you have the passion.

**Comment by clemens-tolboom** [comment]
@I-am-MR-NATE it is not possible to teleport. The slither.io server places you on the map/arena.

With #275 (PR #292) you can MoveToXY defaults to center.

Doing a re-spawn until @ position X,Y is quite slither.io unfriendly and I would vote against as we are sort of guest on their system.

Guess we can close this issue with a WONT FIX?

**Comment by I-am-MR-NATE** [comment]
@Chadski, as far as the code goes, I don't know much about the core of the bot however I do have some ideas to contribute. I have experience in Cisco Networking and basic coding vb.net, LUA, HTML, Css ect. So, if that was a sarcastic comment, I'm just throwing around ideas.

@clemens-tolboom, I can understand it would stress the servers if we were accessing multiple servers but if we were accessing the same server requesting respawns (which surely doesn't require that many resources?), it would have almost no effect on the server you are accessing but that all depends on how the game is coded and what the startup process of the client is when connecting to the slither.io servers. This is just my assumption based on previous game structuring experience in my classes. 

All I know is if I were to make a game, I would save resources at every point possible was trying not to affect the game performance which is why I say requesting different locations multiple times across the same server surely can't take up that much processing power.

**Comment by ChadSki** [comment]
Not being sarcastic! The code is not terribly long, and is divided into separate modules. You wouldn't need to understand the AI part at all, for example.

**Comment by clemens-tolboom** [comment]
[edited]
There is a bot submitting zillions of snakes (_chith3r.com__) which is ruining my game play for sure.

Each entering an arena means injecting a snake which immediately ~~fails~~/dies/disconnected. In our case we would inject say ~ 30 snakes to reach your start position.

I asked @slithergame in https://twitter.com/ClemensTolboom/status/744230849839697921

**Comment by I-am-MR-NATE** [comment]
That may be so, but is that process defined by the game itself or would there be a way we could stay connected to one server rather than **spawn>die/disappear>dissconnect**. I do believe it would be stressful to have a many connections and disconnections.

Is it possible to cut the disconnections and stay connnected to that server?

If so, This would make the process run as **Connect(ONCE) and stay> [loop] spawn>Die [/loop]> reach destination radius> end process**

Also how stressful this could be on the servers depends on what size of the Radius would be if this were to be implemented.  Large radius would mean that people, IF THEY CHOOSE to use it, would only perhaps need to be respawned say 3-5 times to reach their desired area.

**Comment by ChadSki** [comment]
I'm going to close this issue as "won't fix" as @clemens-tolboom suggested, but if you do figure out a way to do it, let us know!
