### ISSUE TITLE
Further prioritize bigger food (at a loss of CPU cycles)

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#39]
What do you guys think of:
- We currently use (distance / size) to calculate priority 
- Instead, we use (distance / size^2) in order to further prioritize larger food. I tested this and it is much better at **not** just ignoring the huge food from a dead snake.
- Perhaps have this feature included with a "high" setting?

**Comment by ermiyaeskandary** [comment]
Do we need this with the latest food clustering algorithm ?

**Comment by ChadSki** [comment]
I like the idea behind the title, but the specific suggested fix probably doesn't apply anymore.

I really like the new [calculate every Nth frame](https://github.com/ErmiyaEskandary/Slither.io-bot/blob/093f700183acde67af6d19e886f80df0c198b24a/bot.user.js#L550-L554) idea. If the bot gets too laggy, we can raise that constant in order to conserve CPU.

**Comment by ChadSki** [comment]
Similar concept implemented [here](https://github.com/ErmiyaEskandary/Slither.io-bot/pull/89)

**Comment by ermiyaeskandary** [comment]
Implemented theoretically. If you disagree with me closing this, please comment and reopen .
